openapi: 3.1.0
info:
  title: This is my SWAGGER
  description: This is a todo list
  version: 1.0
  contact:
    email: nicolaslozoya23@yahoo.com
  servers:
    -url: "http://localhost:5000/"
    description: This is my local server

schemes: [http, https]


paths:
 /todo:
  post:
   summary: Adds a todo to the list
   description: Adds a todo to the list. If a list parameter is provided it add multiple todos in one call.
   produces:
    - application/json
   consumes:
    - application/json
   parameters:
   - in: body
     name: Todos
     schema:
      type: array
      items:
       type: object
       properties:
        id:
         type: integer
        todo:
         type: string
        completed:
         type: boolean



  get:
      summary: Returns a todo list
      description: Returns a list of all todos, if an id is provided, only a single todo is
      parameters:
      - name: ID
        in: query
        required: false 
        schema:
          type: integer
      responses:
       200:
        description: Success
        schema:
         type: array
         items:
          type: object
          properties:
           id:
            type: integer
           todo:
            type: string
           completed:
            type: boolean
       400: 
        description: Query Parameters do not meet requirements
 /todo/{id}:
  delete:
   summary: deletes a todo
   description: Deletes a todo from the list
   parameters:
   - name: path
        in: id



 
  put:
   summary: Updates an existing todo
   description: Updates an existing todo and modifies its data
   produces:
    - application/json
   consumes:
    - application/json
   parameters:
   - in: body
     name: Todos
     schema:
      type: array
      items:
       type: object
       properties:
        id:
         type: integer
        todo:
         type: string
        completed:
         type: boolean
  
        










      

       